import Foundation

// MARK: - Marker

/// Custom UTI tagging our own pasteboard writes so the monitor skips them
/// (otherwise paste-back would loop: write → monitor → reinsert → write).
enum PasteboardMarkers {
    static let internalUTI: String =
        (Bundle.main.bundleIdentifier ?? "fr.alexandretrichot.Crowy") + ".internal"
}

// MARK: - Protocol

enum FilterDecision {
    case accept
    case reject(reason: String)
}

protocol PasteboardFilter {
    func decide(_ snapshot: ClipboardMonitor.PasteboardSnapshot) -> FilterDecision
}

// MARK: - Composite (fail-fast)

/// Snapshot must be accepted by every filter; first `reject` wins.
struct CompositeFilter: PasteboardFilter {
    let filters: [PasteboardFilter]

    func decide(_ snapshot: ClipboardMonitor.PasteboardSnapshot) -> FilterDecision {
        for filter in filters {
            let decision = filter.decide(snapshot)
            if case .reject = decision { return decision }
        }
        return .accept
    }
}

// MARK: - nspasteboard.org conventions

/// Honors the nspasteboard.org "do not record" markers used by 1Password,
/// Bitwarden, KeePassXC, Raycast, etc. See https://nspasteboard.org.
struct NSPasteboardConventionsFilter: PasteboardFilter {

    private static let blockedUTIs: Set<String> = [
        "org.nspasteboard.ConcealedType",                // passwords
        "org.nspasteboard.TransientType",                // transient copy
        "org.nspasteboard.AutoGeneratedType",            // programmatically generated
        "org.nspasteboard.ConcealedAutoGeneratedType",
    ]

    func decide(_ snapshot: ClipboardMonitor.PasteboardSnapshot) -> FilterDecision {
        let utis = Set(snapshot.representations.keys)
        if let matched = utis.first(where: Self.blockedUTIs.contains) {
            return .reject(reason: "nspasteboard.org marker: \(matched)")
        }
        return .accept
    }
}

// MARK: - Internal marker

/// Skips writes made by our own paste-back (tagged with the internal UTI).
struct InternalMarkerFilter: PasteboardFilter {
    func decide(_ snapshot: ClipboardMonitor.PasteboardSnapshot) -> FilterDecision {
        if snapshot.representations.keys.contains(PasteboardMarkers.internalUTI) {
            return .reject(reason: "internal write marker")
        }
        return .accept
    }
}

// MARK: - App blacklist

/// Skips copies from apps the user has blacklisted. The provider is called on
/// every decision so we always see the current prefs without coupling to storage.
struct BlacklistFilter: PasteboardFilter {
    let blacklistedBundleIDs: () -> Set<String>

    func decide(_ snapshot: ClipboardMonitor.PasteboardSnapshot) -> FilterDecision {
        guard let id = snapshot.sourceAppBundleID else { return .accept }
        if blacklistedBundleIDs().contains(id) {
            return .reject(reason: "source app blacklisted: \(id)")
        }
        return .accept
    }
}
